#!/bin/bash
#SBATCH --job-name=FastMatMul
#SBATCH --nodes=5                # 40 nodes
#SBATCH --ntasks-per-node=320     # Number of tasks to be invoked on each node
#SBATCH --mem-per-cpu=1024       # Minimum memory required per CPU (in megabytes)
#SBATCH --time=00:10:00          # Run time in hh:mm:ss
#SBATCH --error=job.%J.out
#SBATCH --output=job.%J.out

echo "Starting at `date`"
echo "Running on hosts: $SLURM_NODELIST"
echo "Running on $SLURM_NNODES nodes."
echo "Running on $SLURM_NPROCS processors."
echo "Job id is $SLURM_JOBID"

mpirun ./a.out

echo "Program finished with exit code $? at: `date`"